app/models.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.orm import relationship
from database import users









class User(users.Model, UserMixin):
    __tablename__ = "users"
    id = users.Column(users.Integer, primary_key=True,autoincrement=True)
    email = users.Column(users.String(250), nullable=False, unique=True)
    username = users.Column(users.String(250), nullable=True, unique=True)
    clippings_filename = users.Column(users.String(250), nullable=True)
    confirmed = users.Column(users.String(10),nullable=True)
    password = users.Column(users.String(1000), nullable=True)
    first_name = users.Column(users.String(250), nullable=True)
    last_name = users.Column(users.String(250), nullable=True)
    continent = users.Column(users.String(250), nullable=True)
    user_photo = users.Column(users.String(250),nullable=True)
    posts = relationship("Posts", back_populates="user")
    books = relationship("Books",back_populates="highlight_owner")


class Posts(users.Model):
    __tablename__ = "posts"
    id = users.Column(users.Integer, primary_key=True, nullable=True,autoincrement=True)
    author_id = users.Column(users.String, users.ForeignKey('users.id'), nullable=True)
    quote_author = users.Column(users.String,nullable=True)
    user = relationship("User", back_populates="posts")
    body = users.Column(users.Text, nullable=True)
    quote = users.Column(users.String(250))
    date = users.Column(users.String(250), nullable=True)
    user_quote = users.Column(users.String(250), nullable=False)
    photo = users.Column(users.String(500), nullable=True)


class Books(users.Model):
    __tablename__ = "highlights"
    id = users.Column(users.Integer, primary_key=True, nullable=True, autoincrement=True)
    highlight_id = users.Column(users.String, users.ForeignKey('users.id'), nullable=True)
    highlight_owner = relationship("User",back_populates="books")
    original_quote = users.Column(users.String,nullable=False)
    writer_quote = users.Column(users.String,nullable=False)
    date_added = users.Column(users.String,nullable=True)
    paper = users.Column(users.Boolean)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, FileField
from wtforms.validators import DataRequired, URL, Email, Length, ValidationError, Regexp,url
from wtforms.validators import email
from email_validator import validate_email, EmailNotValidError
from flask_ckeditor import CKEditorField




class Write(FlaskForm):
    quote = StringField("Post Title:", render_kw={"class": "form-control", "placeholder": "E.g. a short version of the quote above"})
    author = StringField("Who is the Author of the quote?",validators=[DataRequired()])
    body = CKEditorField("Ponder Here:", render_kw={"class": "ckeditor", "data-ckeditor-skin": "moono-lisa", "data-ckeditor-fontSize_defaultLabel": "16px", "data-ckeditor-colorButton_colors": "000000,ffffff", "data-ckeditor-toolbar": "['Bold', 'Italic', 'Underline', '-', 'Link', 'Unlink', '-', 'Image']", "data-ckeditor-customConfig": """
                config.extraPlugins = 'image,link';
                config.removePlugins = 'flash';
                config.toolbarGroups = [                    { name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
                    { name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
                    { name: 'editing', groups: [ 'find', 'selection', 'spellchecker' ] },
                    { name: 'forms', groups: [ 'forms' ] },
                    { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
                    { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ] },
                    { name: 'links', groups: [ 'links' ] },
                    { name: 'insert', groups: [ 'insert' ] },
                    { name: 'styles', groups: [ 'styles' ] },
                    { name: 'colors', groups: [ 'colors' ] },
                    { name: 'tools', groups: [ 'tools' ] },
                    { name: 'others', groups: [ 'others' ] },
                    { name: 'about', groups: [ 'about' ] }
                ];
                """})

    submit = SubmitField("Submit")

class ContributeForm(FlaskForm):
    quote = StringField("Enter your quote here:",validators=[DataRequired()])



class Write_Edit(FlaskForm):
    real_quote = CKEditorField("Edit the author quote")
    quote = StringField("Post title:", render_kw={"class": "form-control", "placeholder": "e.g a short version of the quote here."})
    author = StringField("Who is the Author of the quote?",validators=[DataRequired()])
    body = CKEditorField("Ponder Here:", render_kw={"class": "ckeditor", "data-ckeditor-skin": "moono-lisa", "data-ckeditor-fontSize_defaultLabel": "16px", "data-ckeditor-colorButton_colors": "000000,ffffff", "data-ckeditor-toolbar": "['Bold', 'Italic', 'Underline', '-', 'Link', 'Unlink', '-', 'Image']", "data-ckeditor-customConfig": """
                config.extraPlugins = 'image,link';
                config.removePlugins = 'flash';
                config.toolbarGroups = [                    { name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
                    { name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
                    { name: 'editing', groups: [ 'find', 'selection', 'spellchecker' ] },
                    { name: 'forms', groups: [ 'forms' ] },
                    { name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
                    { name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ] },
                    { name: 'links', groups: [ 'links' ] },
                    { name: 'insert', groups: [ 'insert' ] },
                    { name: 'styles', groups: [ 'styles' ] },
                    { name: 'colors', groups: [ 'colors' ] },
                    { name: 'tools', groups: [ 'tools' ] },
                    { name: 'others', groups: [ 'others' ] },
                    { name: 'about', groups: [ 'about' ] }
                ];
                """})

    submit = SubmitField("Submit")

def my_length_check(form, field):
    if any(c.isdigit() for c in field.data):
        raise ValidationError('Username must not contain any numbers.')

def my_password_length_checker(form, field):
    if len(field.data) < 6:
        raise ValidationError('Your password must have at least 6 characters.')
    if not any(x.isupper() for x in field.data):
        raise ValidationError('Your password must have at least one uppercase letter.')

class Register(FlaskForm):
    email = StringField("Email",validators=[DataRequired(),Email("Please enter a valid e-mail adress")],render_kw={"placeholder": "E-mail"})
    password = PasswordField('Password', [
        DataRequired(),
        Length(min=6),
        Regexp(
            '^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{6,}$',
            message="Your password must contain at least one lowercase letter, one uppercase letter, one digit, and one special character"
        )
    ])
    username = StringField("Username",validators=[DataRequired(),my_length_check,Length(min=6,max=16)],render_kw={"placeholder": "Username"})
    submit = SubmitField("Register")


class ResetPassword(FlaskForm):
    new_password = PasswordField("Enter a new password",validators=[DataRequired()],render_kw={"placeholder": "Password", "class":"input-form"})
    submit = SubmitField("Change Password")


class ForgotPassword(FlaskForm):
    email = StringField("Please enter your E-mail",validators=[DataRequired()],render_kw={"placeholder":"email","class":"input-form"})
    submit = SubmitField("Submit")

app/my_blueprint/views.py
from urllib.parse import urlencode

from flask import Blueprint, render_template, request, redirect, url_for
from flask_mail import Message, Mail

my_blueprint = Blueprint('my_blueprint', __name__,template_folder='templates',static_url_path='/static', static_folder='static')


@my_blueprint.route('/',methods=["POST","GET"])
def coming_soon():
    if request.method == 'POST':
        email = request.form.get('email')
        print(email)
        name = request.form.get('name')
        print(name)
        params = urlencode({'email': email, 'name': name})
        return redirect(url_for('notifications') + '?' + params)
    return render_template('coming-soon.html')

app/templates/Dashboard.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block head %}
 {{ super() }}
 <title>Dashboard | Ponder</title>
  <link rel="stylesheet" type="text/css" href="/static/dashboard-styles.css">
{% endblock %}

{% block content %}
 <body>
    <div class="container">
      <div class="row row-cols-12">
        <nav class="navbar navbar-expand-md navbar-light bg-white fixed-top justify-content-center">
        <div class="col-5">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
              <li class="nav-item {% if request.path == url_for('dashboard') %}active{% endif %}">
                <a class="nav-link" href="{{url_for('dashboard')}}">Dashboard</a>
              </li>
              <li class="nav-item {% if request.path == url_for('account',user_id=current_user.id) %}active{% endif %}">
                <a class="nav-link" href="{{url_for('account',user_id=current_user.id)}}">Account</a>
              </li>
              <li class="nav-item {% if request.path == url_for('search_page',user_id=current_user.id) %}active{% endif %}">
                <a class="nav-link" href="{{url_for('search_page')}}">Paper Reader</a>
              </li>
            </ul>
            </div>
          </div>

        <div class="col mx-auto">
          <div class="ponder-logo-div">
          <a class="navbar-brand mx-auto" href="{{url_for('home')}}" id="ponder-logo">
          <img id="ponder-img"  src="/static/android-chrome-192x192.png" alt="" width="50" height="44" class="d-inline-block align-text-top">Ponder
          </a>
        </div>
        </div>
        </nav>
      </div>
      </div>
          <form action="{{ url_for('dashboard') }}" method="post">
      <div class="container justify-content-center" id="quoteoftheday">
        <div class="row justify-content-center">
          <div class="col-12 text-center">
            <h3 style="font-size:25px;"> Your Kindle Highlights:</h3>
            <div class="small-line"></div>
            </div>
          </div>
        <div class="row-justify-content-center" id="ponder-quote-box">
          <div class="col-12 justify-content-center">
            <blockquote class="quote-ponder blockquote text-center">"{{ quote }}"</blockquote>
            <footer class="text-center">-{{ writer }}</footer>
          </div>
        </div>
      </div>

  <div class="container" id="btn-container">
  <div class="row justify-content-center" id="btn-row">
    <div class="col-6 col-lg-3 justify-content-center" id="previous">
        <a href="{{ url_for('dashboard_previous') }}" class="btn btn btn-lg btn-outline-primary" id="write-button">Previous Quote</a>
    </div>
    <div class="col-6 col-lg-3 justify-content-center">
        <a href="{{url_for('write_from_kindle',quote_id=quote_id)}}" type="submit" class="btn btn btn-lg btn-outline-primary" id="write-button">Write about this quote</a>
    </div>
    <div class="col-6 col-lg-3 justify-content-center" id="next">
        <a href="{{ url_for('dashboard_next') }}"  class="btn btn btn-lg btn-outline-primary" id="write-button">Next Quote</a>
    </div>
  </div>
</div>
          </form>
  {% if post_count <= 3 %}
  <div class="container" id="posts-container">
  <div class="row justify-content-center">
    <div class="col-12">
      <h3 class="other-posts-title">Featured Posts:</h3>
      <div class="small-line2"></div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    {% for post in all_posts %}
    <div class="col-12 col-md-4">
      <a href="{{ url_for('see_post',post_id=post.id) }}" style="text-align:center;">
        <div class="card" id="card-div">
          <img src="{{post_images}}" alt="kindle" class="card-img">
          <div class="card-body">
            <h1 class="card-title">{{post.user_quote}}</h1>
            <p class="card-sub-title"> {{post.quote_author}}</p>
          </div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% else %}
<div class="container" id="posts-container">
  <div id="carouselControls" class="carousel slide" data-ride="carousel">
    <div class="row justify-content-center">
      <div class="col-12">
        <h3 class="other-posts-title">Featured Posts:</h3>
        <div class="small-line2"></div>
      </div>
    </div>

    <div class="carousel-inner justify-content-center">
      {% for post in all_posts %}
      <div class="carousel-item{% if loop.first %} active{% endif %}">
        <div class="container">
          <div class="row" id="carousel-row">
            <div class="col-12 col-md-4 justify-content-center">
              <a href="{{ url_for('see_post', post_id=post.id) }}" style="text-align: center;">
                <div class="card" id="card-div">
                  <img src="{{ post_images }}" alt="kindle" class="card-img">
                  <div class="card-body">
                    <h1 class="card-title">{{ post.user_quote }}</h1>
                    <p class="card-sub-title">{{ post.quote_author }}</p>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <a class="carousel-control-prev" href="#carouselControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

{% endif %}

   </body>
{% endblock %}
{% block footer %}

  {{ super() }}
{% endblock %}
 <script src="static/popper.js"></script>
  <script src="static/bootstrap.min.js"></script>
  <script src="static/main.js"></script>
<script src="https://unpkg.com/typed.js@2.0.16/dist/typed.umd.js"></script>

app/templates/Kindle Upload.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/upload.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <title>The Tech Reader|Ponder</title>
    <link rel="icon" type="image/x-icon" href="static/favicon-32x32.png">
    <!---- Font Awesome ----->
    <script src="https://kit.fontawesome.com/511589a382.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <!-------NavBar ----->
    <div class="container">
      <nav class="navbar navbar-expand-md navbar-light bg-white fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{url_for('home')}}">
          <img src="/static/android-chrome-192x192.png" alt="" width="50" height="44" class="d-inline-block align-text-top">Ponder
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
              <li class="nav-item {% if request.path == url_for('home') %}active{% endif %}">
                <a class="nav-link" aria-current="page" href="{{url_for('home')}}">Home</a>
              </li>
              <li class="nav-item {% if request.path == url_for('log_out') %}active{% endif %}">
                <a class="nav-link" href="{{url_for('log_out')}}">Log Out</a>
              </li>
              <li class="nav-item {% if request.path == url_for('dashboard') %}active{% endif %}">
                <a class="nav-link" href="{{url_for('dashboard')}}">Dashboard</a>
              </li>
              <li class="nav-item {% if request.path == url_for('account',user_id=current_user.id) %}active{% endif %}">
                <a class="nav-link" href="{{url_for('account',redirect_from='index',user_id=current_user.id)}}">Account</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <!----- Main Content ---->
    {% if not_uploaded %}
    <div class="alert alert-warning alert-dismissible fade show text-center" role="alert" id="alert-div">
              We couldn't find your My Clippings file. Remember that the file name must be 'My Clippings'.
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
              </button>
    </div>
    {% endif %}
    <h2 class="big-heading" id="heading2">The Tech Reader</h2>
    <div class="container" id="upload-container" >
      <div class="row">
        <div class="col-12 col-md-6 col-lg-4" id="kindle-auth">
          <div class="card">
            <img src="/static/kindle-logo img.jpg" alt="kindle-upload-logo" class="card-img-top">
            <div class="card-body">
              <h5 class="card-title">Kindle Upload</h5>
              <p class="card-text"> Authenticate your Amazon account with Ponder to automatically get all Kindle Highlights. Get started Now.</p>
              <a href="{{url_for('my_blueprint.coming_soon')}}" class="icon-link" id="auth-link">
              Click to Authenticate
              </a>
              <svg class="bi" width="1em" height="1em">
                <use xlink:href="#chevron-right"></use>
              </svg>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4" id="kindle-upload">
          <div class="card">
            <img src="/static/upload.jpg" alt="My-Clippings" class="card-img-top">
            <div class="card-body">
              <h5 class="card-title">Ancient Upload</h5>
              <p class="card-text"> Click below to upload your "My Clippings.txt" ( located inside your Kindle device ) here.</p>
              <form method="post" enctype="multipart/form-data">
                <div class="custom-file">
                  <input type="file" class="custom-file-input" id="file-input" name="My Clippings">
                  <label class="custom-file-label" for="file-input">Choose file</label>
                </div>
                <button type="submit" class="btn btn-primary btn-upload mt-3" id="upload-button">
                Upload
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
  document.getElementById('file-input').addEventListener('change', function(event) {
    var fileName = event.target.files[0].name;
    var maxFileNameLength = 20; // Adjust this value as needed
    var truncatedFileName = fileName.length > maxFileNameLength ? fileName.slice(0, maxFileNameLength) + '...' : fileName;
    document.getElementById('file-label').innerHTML = truncatedFileName;
  });

     var fileInput = document.getElementById('file-input');
     var label = fileInput.nextElementSibling;

     fileInput.addEventListener('change', function(event) {
     var filename = event.target.value.split('\\').pop();
     label.innerHTML = filename;
      });
</script>
  </body>
  <!----- Footer ----->
  <footer class="footer-16371">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-9 text-center">
          <div class="footer-site-logo mb-4">
            <a href="{{url_for('home')}}">Ponder</a>
          </div>
          <ul class="list-unstyled nav-links mb-5">
            <li><a href="{{ url_for('about') }}">About</a></li>
            <li><a href="{{ url_for('contact') }}">Contact</a></li>
          </ul>
          <div class="social mb-4">
            <h3>Stay in touch</h3>
            <ul class="list-unstyled">
              <li class="in"><a href="#"><i class="bi bi-instagram"></i></a></li>
              <li class="fb"><a href="#"><i class="bi bi-facebook"></i></a></li>
              <li class="tw"><a href="#"><i class="bi bi-twitter"></i></a></li>
              <li class="dr"><a href="#"><i class="bi bi-dribbble"></i></a></li>
            </ul>
          </div>
          <script type="text/javascript" src="https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js" data-name="bmc-button" data-slug="walkingkindle" data-color="#5F7FFF" data-emoji=""  data-font="Cookie" data-text="Buy me a coffee" data-outline-color="#000000" data-font-color="#ffffff" data-coffee-color="#FFDD00" ></script>
          <div class="copyright">
            <p class="mb-0"><small>&copy; Ponder. All Rights Reserved.</small></p>
          </div>
        </div>
      </div>
    </div>
  </footer>
</html>

app/templates/Kindle-Upload.html
<html lang="en">
{% extends 'base.html' %}
{% block head %}
  {{ super() }}
    <link rel="stylesheet" type="text/css" href="/static/upload.css">
    <title>The Tech Reader | Ponder</title>
    <!---- Font Awesome ----->
    <script src="https://kit.fontawesome.com/511589a382.js" crossorigin="anonymous"></script>
            <!------------------- Sweet Alert -------------------->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

{% endblock %}
{% block content %}
  <body>
    <!-------NavBar ----->
    <div class="container">
      <nav class="navbar navbar-expand-md navbar-light bg-white fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand" href="{{url_for('home')}}">
          <img src="/static/android-chrome-192x192.png" alt="" width="50" height="44" class="d-inline-block align-text-top">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
              <li class="nav-item {% if request.path == url_for('home') %}active{% endif %}">
                <a class="nav-link" aria-current="page" href="{{url_for('home')}}">Home</a>
              </li>
              <li class="nav-item {% if request.path == url_for('dashboard') %}active{% endif %}">
                <a class="nav-link" href="{{url_for('dashboard')}}">Dashboard</a>
              </li>
              <li class="nav-item {% if request.path == url_for('search_page') %}active{% endif %}">
                <a class="nav-link" href="{{url_for('search_page')}}">Paper Reader</a>
              </li>
              <li class="nav-item {% if request.path == url_for('account',user_id=current_user.id) %}active{% endif %}">
                <a class="nav-link" href="{{url_for('account',redirect_from='index',user_id=current_user.id)}}">Account</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
    <!----- Main Content ---->
    {% if not_uploaded %}
<script>
  const Toast = Swal.mixin({
    toast: true,
    position: 'top-end',
    showConfirmButton: false,
    timer: 3000,
    timerProgressBar: true,
    didOpen: (toast) => {
      toast.addEventListener('mouseenter', Swal.stopTimer)
      toast.addEventListener('mouseleave', Swal.resumeTimer)
    }
  });

  $(function() {
    Toast.fire({
      icon: 'warning',
      title: 'Parsing failed',
      text: 'We couldn\'t find your My Clippings file, or you uploaded an invalid file." ',
    });
  });
</script>
    {% endif %}
    <!----- Little instruction ----->
        <script>
           var popupShown = localStorage.getItem("popupShownupload");
           if (!popupShown) {
          Swal.fire({
          title: "Welcome to Tech Reader",
          text: "Upload your Kindle quotes manually by plugging in your Kindle Device via USB, and then going to Kindle/Documents. There you will find My Clippings.txt",
          icon: "info",
          confirmButtonText: "Got it!"
        });
        localStorage.setItem("popupShownupload", true);
        }
       </script>
    <h2 class="big-heading" id="heading2">The Tech Reader</h2>
    <div class="container" id="upload-container" >
      <div class="row">
        <div class="col-12 col-md-6 col-lg-4" id="kindle-auth">
          <div class="card">
            <img src="/static/kindle-logo img.jpg" alt="kindle-upload-logo" class="card-img-top">
            <div class="card-body">
              <h5 class="card-title">Kindle Upload</h5>
              <p class="card-text"> Authenticate your Amazon account with Ponder to automatically get all Kindle Highlights. Get started Now.</p>
              <a href="{{url_for('my_blueprint.coming_soon')}}" class="icon-link" id="auth-link">
              Click to Authenticate
              </a>
              <svg class="bi" width="1em" height="1em">
                <use xlink:href="#chevron-right"></use>
              </svg>
            </div>
          </div>
        </div>
        <div class="col-12 col-md-6 col-lg-4" id="kindle-upload">
          <div class="card">
            <img src="/static/upload.jpg" alt="My-Clippings" class="card-img-top">
            <div class="card-body">
              <h5 class="card-title">Ancient Upload</h5>
              <p class="card-text"> Click below to upload your "My Clippings.txt" ( located inside your Kindle device ) here.</p>
              <form method="post" enctype="multipart/form-data">
                <div class="custom-file">
                  <input type="file" class="custom-file-input" id="file-input" name="My Clippings">
                  <label class="custom-file-label" for="file-input">Choose file</label>
                </div>
                <button type="submit" class="btn btn-primary btn-upload mt-3" id="upload-button">
                Upload
                </button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
  document.getElementById('file-input').addEventListener('change', function(event) {
    var fileName = event.target.files[0].name;
    var maxFileNameLength = 20; // Adjust this value as needed
    var truncatedFileName = fileName.length > maxFileNameLength ? fileName.slice(0, maxFileNameLength) + '...' : fileName;
    document.getElementById('file-label').innerHTML = truncatedFileName;
  });

     var fileInput = document.getElementById('file-input');
     var label = fileInput.nextElementSibling;

     fileInput.addEventListener('change', function(event) {
     var filename = event.target.value.split('\\').pop();
     label.innerHTML = filename;
      });
</script>
  </body>
{% endblock %}

{% block footer %}
{{ super() }}
{% endblock %}
</html>

app/templates/file-not-selected.html
<!DOCTYPE html>
<html>
  <head>
    <title>No File Selected|Ponder</title>
    <link rel="stylesheet" type="text/css" href="static/not-selected-styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap" rel="stylesheet">
  </head>
  <body>
    {% if wrong == "wrong" %}
    <div class="container">
      <h1>You've selected a wrong file.</h1>
      <p>Or our robot slaves seems to think so.</p>
      <button onclick="goBack()">Try again</button>
    </div>
    {% elif redirect_from == 'see_post' %}
    <div class="container">
      <h1>Ooops, looks like you haven't wrote anything  on this topic</h1>
      <p>Not sure how it got here though.</p>
      <button onclick="goBack()">Try again</button>
    </div>
    {% else %}
    <div class="container">
      <h1>No File Selected</h1>
      <p>Please select a file to upload.</p>
      <button onclick="goBack()">Go Back</button>
    </div>
    {% endif %}
    <script>
      function goBack() {
        window.history.back();
      }
    </script>
  </body>
</html>